name: bio-transformers-dev
channels:
  #- conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip=20.2.4
  - pip:
    - pre-commit==2.2.0
    - biopython==1.78
    - fair-esm==0.3.1
    - m2r2==0.2.7
    - numpy>=1.16
    - pandas>=1.2.3
    - pytest==6.2.4
    - pytest-cov==2.12.0
    - pytorch_lightning>=1.3.3
    - scikit-learn>=0.22.2
    - sphinx
    - sphinx-notfound-page==0.6
    - sphinx_rtd_theme==0.5.2
    - sphinx_tabs==2.1.0
    - sphinx-book-theme
    - torch>=1.7.0
    - torchmetrics==0.3.2
    - tqdm>=4.60.0
    - transformers>=4.6.1,<4.7
    - myst-parser
    - myst-nb
